server:
  port: 7030

spring:
  application:
    name: simple-demo-collection
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    settings:
      number_format: 0.##
    suffix: .ftl
    template-loader-path: classpath:/templates/
  cloud:
    nacos:
      server-addr: http://127.0.0.1:8848
      username:
      password:
      discovery:
        registerEnabled: true
        namespace:
      config:
        namespace:
        file-extension: yml
  config:
    import:
      - nacos:application.yml
      - nacos:simple-single-collection.yml?group=DEFAULT_GROUP&refreshEnabled=false
simple:
  redisson:
    enabled: true
    type:  standalone
    address:  127.0.0.1:6379
    password: password
    database: 0
  ## 无redisson配置情况下，默认开启Socket单机
  socket:
    #缺省项为false
    enabled: true
    port: 7031
    upgradeTimeout: 1000000
    pingTimeout: 6000000
    pingInterval: 25000
  grpc:
    server:
      enabled: true
      port: 7032
    client:
      enabled: true
      channel:
        grpc-server-hello:
          address: '127.0.0.1:7032'
        grpc-server-person:
          address: '127.0.0.1:7032'
  s3:
    enabled: true
    accessKey: RKcxrJ80qTgziqaH
    secretKey: pVlB5bm0vIA6aidjWLG8ZfKUIuB7dNUC
    endpoint: 127.0.0.1:9000
  freemarker:
    resourceVoList:
      # resourceHandler：访问的前缀 resourceLocations：真实路径
      - resourceHandler:  /Users/**
        resourceLocations:  file:/Users/
  dict:
    dictImplBeanName: remoteDictServiceImpl
    remoteBaseUrl: http://127.0.0.1:11120
  encrypt:
    rsa:
      publicKey: |
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6ewfgrp97KoD7beFHnzl
        x3Ln1kvH/6svv7NqswrXqh3xAvqvSpSJ87Z4EbMWzQyuzpAV0lJfwKzUMgIBn+6E
        Kc5tnzg46sMb0VroKdphOVnCQYv7n0jacBXazxxMGngyIaGLSN/Kc1K/3gx+bQUq
        kBZ/zDbG7VF4S6Q/FNsMWFFxZJ5ny7b14XCwqbu94uoXebrB0JO4ZoMmCekDiq48
        oNugrsHfLmO1kfrnO6Tf8Xsfggz+diNsFR/qrZ/0ofrz3rr3JQ7te9sN3Sn5sA+I
        CcfryhDRyOdIi29Xp1pU2xxOJ7ZCC6wq+pEXWWRQR45PDbmi1RdheE8benDPeO/s
        vwIDAQAB
      privateKey: |
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDp7B+Cun3sqgPt
        t4UefOXHcufWS8f/qy+/s2qzCteqHfEC+q9KlInztngRsxbNDK7OkBXSUl/ArNQy
        AgGf7oQpzm2fODjqwxvRWugp2mE5WcJBi/ufSNpwFdrPHEwaeDIhoYtI38pzUr/e
        DH5tBSqQFn/MNsbtUXhLpD8U2wxYUXFknmfLtvXhcLCpu73i6hd5usHQk7hmgyYJ
        6QOKrjyg26Cuwd8uY7WR+uc7pN/xex+CDP52I2wVH+qtn/Sh+vPeuvclDu172w3d
        KfmwD4gJx+vKENHI50iLb1enWlTbHE4ntkILrCr6kRdZZFBHjk8NuaLVF2F4Txt6
        cM947+y/AgMBAAECggEAReidWjJl487Dsc2A6SWmfj7m7nJjaRM+B+qU3sFExsCA
        AMXukTlnKQDFTXTaQZmivHTvMJYRq8F7AR78YVGlCeF5fXYN/IsmyyCB9dAf8kXS
        +kfdgTMCpTDC3da1H8wAH3Dp8XOAS4rVcIUHW4mJuNogg2VzegU5EFIb0B3OyK2r
        +E3qSHGRxrSeZJKRvvJ4UqHCMG/GynnKRw8Lr8k8sKtakmscPEelf38nUWkrA7Rp
        1Z2lxm7jbRbcZwYYCZF011rgk3ZBpEX/SB4206rubyyigh7e8SP9KOrjHlLON050
        YnhjNpGwoVEyOZG4l/N0jzRTFYzp+bqCoQLMr19lYQKBgQD+H7mp8rT6XR0Vv+d+
        ALNFGd583+dSdR2bAyaLGoigF4kZlCRejwaPqxG0peDsJYVdEUTM0NigOkjNvfGM
        H0CA20YGyh0j/X4v6xyI7j52mWZBVojcYxwMPxxAkR/Qt4g/xuuckbrthz0qJwYR
        p2O5yv4yvtXyqbTjCNtYARSpRwKBgQDrpjfqOwnz4U4t97/vCRVK0X6sYMRahBfQ
        z+X12jB63i0GcLpunodlH1dRykbPKV6ky8/p3HD21MWUOD4XlQihy6Ywjaxrlng3
        ZiAr2cPdktkBErZlwIR+Za5LzDKqshdJ46uK54pOiJvmJ5/2FpxydU2+9NI1ZIqi
        vV/a7tLcyQKBgGsHTZkIQbTYlrFcW9Ez1k0aMhyB6NlPviJVV1xq1nQmtXVycUbq
        EidcM17UJkEPJHYoGcPxiesh4RvWDe+oEfCzaXDemxtXXlgsO55oSSKGRQzrt0Sq
        8VsvEWUYOkAbrGTAEOemcQYtWVNxkBrLVzMfDaStv0ous6KTTl5oRh1tAoGBAM5P
        7rByFBqjbbEtMat0BmJE3GTLK94bvEYjXrBK4RsRndX/qBnlTaEpOWfwcuI41BXw
        Iw4a5AQW8Qz92M8Iuk/9Xnkv8H8ZdBL8pLn/pE4/nSIlYe/gB6AqIdlW5B0yYtVc
        MPoiEaMEU4nDs3bfAQXs0a6X5dq9NeuZZWzmn1KRAoGAVzPFFjIal9VdzBHjxdCe
        d1FSPCDAUpyR4Qs3oMMZf2+dfTowxjBJkETXz67nnSVr4F3ePSD54JFXoLPzwQuR
        sbpjvlsjlLu5gKG3vgkIrLkQqejOFGj3yUkLw43PN3Xkb5YXaxU3jOoGr7TZCxGc
        bIBtZFeFzMkYFnnaL6Boye4=